<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Ievgeniias-MBP.fios-router.home" name="com.fnoor.FundraisingTest.STRIPE" tests="10" failures="1" timestamp="2020-08-21T11:02:18 EDT" time="130.038" errors="0">
  <testcase name="stripeSEPAsingle" time="7.701" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeSingle" time="10.641" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeSingle3D" time="17.574" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeRecurring3D" time="11.900" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeIDEALsingleABN" time="18.502" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeSEPArecurring" time="7.748" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeBancontactSingle" time="16.491" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeIDEALsingleASN" time="17.872" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeRecurring" time="10.466" classname="com.fnoor.FundraisingTest.STRIPE"/>
  <testcase name="stripeIDEALsingleASNRefund" time="11.143" classname="com.fnoor.FundraisingTest.STRIPE">
    <failure type="java.lang.AssertionError" message="Original receipt not present">
      <![CDATA[java.lang.AssertionError: Original receipt not present
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at com.fnoor.PageFields.validateOriginalReceipt(PageFields.java:745)
at com.fnoor.FundraisingTest.STRIPE.stripeIDEALsingleASNRefund(STRIPE.java:703)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- stripeIDEALsingleASNRefund -->
</testsuite> <!-- com.fnoor.FundraisingTest.STRIPE -->
